name: Compile blueprint

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  workflow_dispatch:        # Allow manual triggering of the workflow from the GitHub Actions interface

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true

      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Build project
        uses: leanprover/lean-action@v1
        with:
          build: true
          lint: false

      - name: Compile blueprint and homepage
        uses: leanprover-community/docgen-action@main
        with:
          api-docs: false
          blueprint: true
          homepage: home_page
